frontend:
  image: lyzhang1999/frontend
  tag: '1276e23'
  autoscaling:
    averageUtilization: 90
backend:
  image: ntops/backend:1ce4d79
  tag: '1276e23'
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
